# DO NOT EDIT THIS FILE!
#
# Python module Client generated by omniidl

import omniORB
omniORB.updateModule("Client")

# ** 1. Stub files contributing to this module
import client_idl

# ** 2. Sub-modules

# ** 3. End
