# DO NOT EDIT THIS FILE!
#
# Python module Server__POA generated by omniidl

import omniORB
omniORB.updateModule("Server__POA")

# ** 1. Stub files contributing to this module
import server_idl

# ** 2. Sub-modules

# ** 3. End
